// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SL_Bullion.DAL;

#nullable disable

namespace SL_Bullion.Migrations
{
    [DbContext(typeof(BullionDbContext))]
    partial class BullionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SL_Bullion.Models.Bank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("accountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankLogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("ifscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tblBank");
                });

            modelBuilder.Entity("SL_Bullion.Models.BankLogo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblBankLogo");
                });

            modelBuilder.Entity("SL_Bullion.Models.BankRate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<double>("conversionGold")
                        .HasColumnType("float");

                    b.Property<double>("conversionSilver")
                        .HasColumnType("float");

                    b.Property<double>("customDutyGold")
                        .HasColumnType("float");

                    b.Property<double>("customDutySilver")
                        .HasColumnType("float");

                    b.Property<double>("divisionGold")
                        .HasColumnType("float");

                    b.Property<double>("divisionSilver")
                        .HasColumnType("float");

                    b.Property<double>("gstGold")
                        .HasColumnType("float");

                    b.Property<double>("gstSilver")
                        .HasColumnType("float");

                    b.Property<double>("interBankGold")
                        .HasColumnType("float");

                    b.Property<double>("interBankSilver")
                        .HasColumnType("float");

                    b.Property<double>("marginGold")
                        .HasColumnType("float");

                    b.Property<double>("marginSilver")
                        .HasColumnType("float");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiplyGold")
                        .HasColumnType("float");

                    b.Property<double>("multiplySilver")
                        .HasColumnType("float");

                    b.Property<double>("premiumGold")
                        .HasColumnType("float");

                    b.Property<double>("premiumSilver")
                        .HasColumnType("float");

                    b.Property<string>("spotTypeGold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spotTypeSilver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblBankRate");
                });

            modelBuilder.Entity("SL_Bullion.Models.Coin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("buyCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("buyPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("division")
                        .HasColumnType("float");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<bool>("isStock")
                        .HasColumnType("bit");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiply")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sellCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("sellPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblCoin");
                });

            modelBuilder.Entity("SL_Bullion.Models.CoinBank", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<double>("conversionGold")
                        .HasColumnType("float");

                    b.Property<double>("conversionSilver")
                        .HasColumnType("float");

                    b.Property<double>("customDutyGold")
                        .HasColumnType("float");

                    b.Property<double>("customDutySilver")
                        .HasColumnType("float");

                    b.Property<double>("divisionGold")
                        .HasColumnType("float");

                    b.Property<double>("divisionSilver")
                        .HasColumnType("float");

                    b.Property<double>("gstGold")
                        .HasColumnType("float");

                    b.Property<double>("gstSilver")
                        .HasColumnType("float");

                    b.Property<double>("interBankGold")
                        .HasColumnType("float");

                    b.Property<double>("interBankSilver")
                        .HasColumnType("float");

                    b.Property<double>("marginGold")
                        .HasColumnType("float");

                    b.Property<double>("marginSilver")
                        .HasColumnType("float");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiplyGold")
                        .HasColumnType("float");

                    b.Property<double>("multiplySilver")
                        .HasColumnType("float");

                    b.Property<double>("premiumGold")
                        .HasColumnType("float");

                    b.Property<double>("premiumSilver")
                        .HasColumnType("float");

                    b.Property<string>("spotTypeGold")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spotTypeSilver")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblCoinBank");
                });

            modelBuilder.Entity("SL_Bullion.Models.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bannerApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bannerWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("email1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("goldDifferance")
                        .HasColumnType("int");

                    b.Property<bool>("isBuy")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoinRate")
                        .HasColumnType("bit");

                    b.Property<bool>("isHigh")
                        .HasColumnType("bit");

                    b.Property<bool>("isLow")
                        .HasColumnType("bit");

                    b.Property<bool>("isRate")
                        .HasColumnType("bit");

                    b.Property<bool>("isSell")
                        .HasColumnType("bit");

                    b.Property<string>("marqueeBottom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("marqueeTop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("number1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("silverDifferance")
                        .HasColumnType("int");

                    b.Property<string>("whatsAppNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblContact");
                });

            modelBuilder.Entity("SL_Bullion.Models.Feedback", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblFeedback");
                });

            modelBuilder.Entity("SL_Bullion.Models.Kyc", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("companyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gstNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ifsc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeMobile1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("officeMobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("panNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("partnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("residenceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblKyc");
                });

            modelBuilder.Entity("SL_Bullion.Models.Master", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fcmKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isBank")
                        .HasColumnType("bit");

                    b.Property<bool>("isClientRate")
                        .HasColumnType("bit");

                    b.Property<bool>("isCoin")
                        .HasColumnType("bit");

                    b.Property<bool>("isFeedback")
                        .HasColumnType("bit");

                    b.Property<bool>("isJewellery")
                        .HasColumnType("bit");

                    b.Property<bool>("isKyc")
                        .HasColumnType("bit");

                    b.Property<bool>("isOtr")
                        .HasColumnType("bit");

                    b.Property<bool>("isUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("symbol")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("versionAndroid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("versionIos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblMaster");
                });

            modelBuilder.Entity("SL_Bullion.Models.MasterLogin", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblMasterLogin");
                });

            modelBuilder.Entity("SL_Bullion.Models.Otr", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("firmname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblOtr");
                });

            modelBuilder.Entity("SL_Bullion.Models.ReferanceSymbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<bool>("isMaster")
                        .HasColumnType("bit");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblReferanceSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.Symbol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("buyCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("buyPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("changePremiumDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("digit")
                        .HasColumnType("int");

                    b.Property<double>("division")
                        .HasColumnType("float");

                    b.Property<double>("gst")
                        .HasColumnType("float");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("index")
                        .HasColumnType("int");

                    b.Property<bool>("isView")
                        .HasColumnType("bit");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("multiply")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productType")
                        .HasColumnType("int");

                    b.Property<string>("rateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("sellCommonPremium")
                        .HasColumnType("float");

                    b.Property<string>("sellPremium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uniqueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblSymbol");
                });

            modelBuilder.Entity("SL_Bullion.Models.Update", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("tblUpdate");
                });
#pragma warning restore 612, 618
        }
    }
}
